### ISSUE TITLE
Ajouter le paramétrage pour tous les AM qui s'appliquent à un alinéa spécifique

### ISSUE THREAD

**Issue by remidbs** [Envinorma/envinorma-data#90]
Deux cas:
- la liste des alinéas est exhaustive : pas de warning + pas de précision des alinéas
- la liste des alinéas n'est pas exhaustive : le traiter en warning

Pour les deux AM 2925 D, l'alinéa n'est pas renseigné dans les alinéas : changer ça

# Liste exhaustive des modifications

## 2101 D
**Actuellement** 
JORFTEXT000028409472 applicable aux alinéas 1, 2 et 3
JORFTEXT000000464327 applicable à l'alinéa 4

**En base de données** 

rub|reg|al|occs
-- | -- | -- | --
2101 | D | 1-c | 942
2101 | D | 2-c | 1404
2101 | D | 3 | 244
2101 | D | 4 | 23

**TODO**
- [x] changer 1 et 2 par 1-c et 2-c

## 2910 D
JORFTEXT000037284510

- [x] Enlever l'alinéa

## 1414 D
**Actuellement**
JORFTEXT000033560858 pour l'alinéa 2
JORFTEXT000022865723 pour l'alinéa 3

**En db**
rub|reg|al|occs
-- | -- | -- | --
1414 | D | 2-d | 4
1414 | D | 3 | 772

**TODO**
- [x] Remplacer 2 par 2-d

## 2130 D
**Actuellement** 
JORFTEXT000033560858 pour l'alinéa 2

**En db**
Que de l'alinéa 2-b

**TODO**
- [x] Supprimer l'alinéa

## 2925 D
**Actuellement**
JORFTEXT000000584145 pour l'alinéa 1
JORFTEXT000037311523 pour l'alinéa 2

**En db**

rub|reg|al|occs
-- | -- | -- | --
2925 | D | # | 7
2925 | D | 1 | 5280
2925 | D | 2 | 25

**TODO**
- [x] Rien à faire.

## 2940 - E

**Actuellement**
JORFTEXT000041876133 applicable aux alinéas 1, 2 et 3 

**TODO**
- [x] c'est exhaustif, donc supprimer les alinéas

## Autres suppressions 
- [x] 2711 - E Alinéa à supprimer de l'arrêté JORFTEXT000037032383
- [x] 2713 - E Alinéa à supprimer de l'arrêté JORFTEXT000037032383
- [x] 2714 - E Alinéa à supprimer de l'arrêté JORFTEXT000037032383 
- [x] 2716 - E Alinéa à supprimer de l'arrêté JORFTEXT000037032383 
- [x] 2710 - E supprimer alinéa de JORFTEXT000025634333
- [x] 1434 - D supprimer alinéa de JORFTEXT000020008930

## 2712 - E
**Actuellement**
- JORFTEXT000026695033 applicable à l'alinéa 1
- JORFTEXT000037032238 applicable à l'alinéa 3
- JORFTEXT000025835110 applicable à tous les alinéas (icpe avec agrément)

**En db**

rub|reg|al|occs
-- | -- | -- | --
2712 | E | 1 | 2783
2712 | E | 1-b | 3
2712 | E | 3-a | 11
2712 | E | 3-b | 18

**TODO**
- [x] JORFTEXT000026695033 applicable aux alinéas 1 (pas 1-b pour éviter d'induire en erreur l'utilisateur)
- [x] JORFTEXT000037032238 applicable aux alinéas 3-a et 3-b

## 2910 - E

JORFTEXT000037284611 applicable aux alinéas B et C

rub|reg|al|occs
-- | -- | -- | --
2910 | E | A-1 | 944
2910 | E | B-1 | 133
2910 | E | B-2-a | 2

**TODO**

- [x] Enlever les alinéas associés

## 2710 - D

**Actuellement**
JORFTEXT000025687401 applicable à l'alinéa 1 
JORFTEXT000025687415 applicable à l'alinéa 2

**En db**

rub|reg|al|occs
-- | -- | -- | --
2710 | D | 1-b | 1469
2710 | D | 2 | 73
2710 | D | 2-b | 404
2710 | D | 2-c | 2

**TODO**

- [x] Changer 1 par 1-b et 2 par 2 et 2-b (2-c n'existe pas dans la nomenclature)

## 2760 - E
**Actuellement**
JORFTEXT000029893853 applicable à tous les alinéas
JORFTEXT000037832596 applicable à l'alinéa 2.a

**En db**

rub | reg | al | occs
-- | -- | -- | --
2760 | E | 3 | 1175

**TODO**
- [x] JORFTEXT000029893853 s'applique vraiment à tous les alinéas ? ce n'est pas ce que laisse entendre la [nomenclature](https://aida.ineris.fr/sites/default/files/gesdoc/30296/BrochureNom_v50bispublicv2.pdf) (page 31), il semble que seul l'alinéa 3 soit concerné
- [x] JORFTEXT000037832596 s'applique bien à 2.a seulement. Changer 2.a en 2-a

## 2760 - A
**Actuellement**
JORFTEXT000032282438 s'applique aux alinéas 1 et 2
JORFTEXT000032275960 s'applique à tous les alinéas

**En db**
rub | reg | al | occs
-- | -- | -- | --
2760 | A | 1 | 64
2760 | A | 2 | 3
2760 | A | 2-b | 387
2760 | A | 4 | 2

**TODO**
- [x] JORFTEXT000032282438 s'applique à quels alinéas ? pas très clair
- [x] JORFTEXT000032275960 semble en fait s'appliquer seulement aux déchets non dangereux, à savoir 2-b

## 2160-D
**Actuellement**
JORFTEXT000018049814 applicable aux alinéas 1 et 2

**En db**
rub | reg | al | occs
-- | -- | -- | --
2160|D|1-b|122
2160|D|2-b|259

**TODO**
- [x] Supprimer les alinéas dans JORFTEXT000018049814

## 1434-A
**Actuellement**
JORFTEXT000000190990 applicable à l'alinéa 1
JORFTEXT000019994396 applicable à l'alinéa 1
JORFTEXT000024778832 applicable à l'alinéa 2

**En db**
rub | reg | al | occs
-- | -- | -- | --
1434 | A | 1-a | 280
1434 | A | 2 | 500

**TODO**
- dans ces 3 ams, remplacer 1 par 1-a et laisser 2 comme il est.

## 2915-E

**TODO**
- [x] supprimer l'alinéa dans JORFTEXT000041875990

## 2930-E

**TODO**
- [x] supprimer l'alinéa dans JORFTEXT000041876039

## 2781-E

**TODO**
- [x] supprimer l'alinéa dans JORFTEXT000022727437 (il est en fait applicable aux deux alinéas)

## 2781-D

**TODO**
- [x] supprimer l'alinéa dans JORFTEXT000021334587

## 2792-D
- [x] supprimer l'alinéa dans JORFTEXT000038528312

## 2680-D

**TODO**
- [x] supprimer l'alinéa dans JORFTEXT000000194255

## 2210-D
**Actuellement**
AM JORFTEXT000000418135 -> tous alinéas
AM JORFTEXT000039397758 -> alinéa 3

**En db**
rub | reg | al | occs
-- | -- | -- | --
2210 | D | 2 | 27

**TODO**
- [x] JORFTEXT000000418135 correspond en fait à l'alinéa 2
- [x] JORFTEXT000039397758 correspond bien à l'alinéa 3

## 2793-D
**Actuellement**
JORFTEXT000029964686 alinéa 1
JORFTEXT000036126905 alinéa 3
JORFTEXT000029964692 alinéa 2

**En db**
rub | reg | al | occs
-- | -- | -- | --
2793 | D | 1-c | 1
2793 | D | 2-b | 22
2793 | D | 3-a | 3

**TODO**
- [x] JORFTEXT000029964686 alinéa 1-c
- [x] JORFTEXT000036126905 alinéa 3-a
- [x] JORFTEXT000029964692 alinéa 2-b

## 2731-E

**TODO**
- [x] supprimer l'alinéa JORFTEXT000031259868

## 2731-D
La rubrique semble supprimée. On peut supprimer l'AM, le régime étant occurrent seulement 3 fois.
